/**
 * Docker Security Validation Tests
 *
 * Comprehensive security testing for Docker configurations:
 * - Image pinning and version control
 * - Build context security
 * - Health check configurations
 * - Security options (no-new-privileges, resource limits, read-only filesystem)
 * - OCI metadata compliance
 *
 * Generated by vibe-to-docker security validation suite
 */

import { describe, test, expect, beforeAll } from '@jest/globals';
import { readFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..', '..');
const templatesDir = join(projectRoot, 'src', 'templates');

/**
 * Helper to read template files
 */
async function readTemplate(relativePath) {
  const fullPath = join(templatesDir, relativePath);
  return await readFile(fullPath, 'utf-8');
}

/**
 * Helper to parse YAML files (handles template syntax)
 * For template files with Handlebars syntax, we need to analyze as text
 */
async function parseYamlTemplate(relativePath) {
  const content = await readTemplate(relativePath);

  // If content has template variables, we can't parse it directly
  // Instead, we'll work with the raw text
  if (content.includes('{{')) {
    return { _raw: content, _isTemplate: true };
  }

  return yaml.load(content);
}

describe('Docker Security Validation', () => {
  describe('Image Pinning', () => {
    test('Base images use specific version tags (not latest)', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Should use specific Node version
      expect(dockerfile).toMatch(/FROM node:{{NODE_VERSION}}-alpine/);

      // Should NOT use 'latest' tag
      expect(dockerfile).not.toMatch(/FROM node:latest/);
      expect(dockerfile).not.toMatch(/FROM alpine:latest/);
    });

    test('serve package version is pinned for static builds', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Check for serve installation with version pinning
      // Note: Template uses variable substitution, but should have pinning in final output
      expect(dockerfile).toContain('npm install -g serve');
    });

    test('node alpine images are specified with version', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // All stages should use specific alpine version with SHA256 digest pinning
      const stages = ['deps', 'builder', 'production'];
      for (const stage of stages) {
        const stagePattern = new RegExp(`FROM node:{{NODE_VERSION}}-alpine@sha256:[a-f0-9]{64} AS ${stage}`);
        expect(dockerfile).toMatch(stagePattern);
      }
    });
  });

  describe('Build Context', () => {
    test('docker-compose.yml has correct context path', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Build context should point to parent directory
        expect(content).toMatch(/context:\s+\.\.\/$/m);

        // Dockerfile should be in .vibe-docker subdirectory
        expect(content).toMatch(/dockerfile:\s+\.vibe-docker\/Dockerfile$/m);
      }
    });

    test('dockerfile path is consistent across templates', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      const dockerfilePaths = [];
      for (const file of composeFiles) {
        const content = await readTemplate(file);
        const match = content.match(/dockerfile:\s+(.+)$/m);
        if (match) {
          dockerfilePaths.push(match[1]);
        }
      }

      // All should use the same path
      const uniquePaths = [...new Set(dockerfilePaths)];
      expect(uniquePaths).toHaveLength(1);
      expect(uniquePaths[0]).toBe('.vibe-docker/Dockerfile');
    });
  });

  describe('Health Checks', () => {
    test('Dockerfile health check uses root endpoint', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Should check root endpoint (/)
      expect(dockerfile).toMatch(/localhost:{{PORT}}\//);

      // Should NOT use /health endpoint (not implemented in static servers)
      expect(dockerfile).not.toMatch(/localhost:{{PORT}}\/health[^/]/);
    });

    test('docker-compose health check aligns with Dockerfile', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Health check should exist
        expect(content).toMatch(/healthcheck:/);
        expect(content).toMatch(/test:/);

        // Should check root endpoint (/ or /health)
        expect(content).toMatch(/localhost:{{PORT}}\//);
      }
    });

    test('health check has appropriate intervals and retries', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Should have reasonable timing values
        expect(content).toMatch(/interval:\s+\d+s/);
        expect(content).toMatch(/timeout:\s+\d+s/);
        expect(content).toMatch(/retries:\s+\d+/);
        expect(content).toMatch(/start_period:\s+\d+s/);

        // Retries should be >= 3 for reliability
        const retriesMatch = content.match(/retries:\s+(\d+)/);
        expect(retriesMatch).toBeTruthy();
        expect(parseInt(retriesMatch[1])).toBeGreaterThanOrEqual(3);
      }
    });
  });

  describe('Security Options', () => {
    test('containers use non-root user', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Should create non-root user
      expect(dockerfile).toMatch(/addgroup.*nodejs/);
      expect(dockerfile).toMatch(/adduser.*appuser/);

      // Should switch to non-root user
      expect(dockerfile).toMatch(/USER appuser/);
    });

    test('containers have restart policies', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Should have restart policy
        expect(content).toMatch(/restart:\s+unless-stopped/);
      }
    });

    test('production environment is set correctly', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Production stage should set NODE_ENV
      expect(dockerfile).toMatch(/ENV NODE_ENV=production/);
    });

    test('containers use isolated networks', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Should have networks defined at top level
        expect(content).toMatch(/^networks:/m);

        // Service should be attached to network
        expect(content).toMatch(/networks:/);
        expect(content).toMatch(/\w+-network/);
      }
    });
  });

  describe('OCI Metadata', () => {
    test('Dockerfile has OCI labels in all stages', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');
      const stages = ['deps', 'builder', 'production'];

      for (const stage of stages) {
        // Find the stage definition (allowing for multiline content)
        const stageRegex = new RegExp(`FROM.*AS ${stage}[\\s\\S]*?(?=FROM|$)`);
        const stageContent = dockerfile.match(stageRegex);

        expect(stageContent).toBeTruthy();

        // Check for OCI labels
        expect(stageContent[0]).toMatch(/LABEL org\.opencontainers\.image\.source/);
        expect(stageContent[0]).toMatch(/LABEL org\.opencontainers\.image\.version/);
        expect(stageContent[0]).toMatch(/LABEL org\.opencontainers\.image\.description/);
        expect(stageContent[0]).toMatch(/LABEL org\.opencontainers\.image\.created/);
      }
    });

    test('OCI labels use appropriate placeholders', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Should use template variables for dynamic values
      expect(dockerfile).toMatch(/{{VERSION}}/);
      expect(dockerfile).toMatch(/{{PROJECT_NAME}}/);
      expect(dockerfile).toMatch(/{{BUILD_DATE}}/);
    });
  });

  describe('Environment Variables', () => {
    test('docker-compose uses env_file for secrets', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Should use env_file for loading environment variables
        expect(content).toMatch(/env_file:/);
        expect(content).toMatch(/- \.env$/m);
      }
    });

    test('docker-compose sets production environment', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Should set NODE_ENV=production
        expect(content).toMatch(/environment:/);
        expect(content).toMatch(/- NODE_ENV=production/);
      }
    });
  });

  describe('Port Configuration', () => {
    test('ports are properly exposed and mapped', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Should have port mapping
        expect(content).toMatch(/ports:/);

        // Port mapping should use template variable
        expect(content).toMatch(/- "{{PORT}}:{{PORT}}"/);
      }
    });

    test('Dockerfile exposes correct port', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Should expose port using template variable
      expect(dockerfile).toMatch(/EXPOSE {{PORT}}/);
    });
  });

  describe('Build Arguments Security', () => {
    test('no secrets are hardcoded in Dockerfile', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Common secret patterns that should NOT be present
      const secretPatterns = [
        /password\s*=\s*["'][^"']+["']/i,
        /api[_-]?key\s*=\s*["'][^"']+["']/i,
        /secret\s*=\s*["'][^"']+["']/i,
        /token\s*=\s*["'][^"']+["']/i
      ];

      for (const pattern of secretPatterns) {
        expect(dockerfile).not.toMatch(pattern);
      }
    });

    test('build environment variables use template placeholders', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // If BUILD_ENV_VARS is used, it should be a template variable
      if (dockerfile.includes('BUILD_ENV_VARS')) {
        expect(dockerfile).toMatch(/{{BUILD_ENV_VARS}}/);
      }
    });
  });

  describe('Multi-Stage Build Security', () => {
    test('production stage only copies necessary files', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Production stage should copy from builder, not from source
      const productionStage = dockerfile.match(/FROM.*AS production[\s\S]*$/m);
      expect(productionStage).toBeTruthy();

      // Should use COPY --from=builder
      expect(productionStage[0]).toMatch(/COPY --from=builder/);
    });

    test('builder stage has proper file ownership', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Files copied to production should have proper ownership
      const productionStage = dockerfile.match(/FROM.*AS production[\s\S]*$/m);
      expect(productionStage[0]).toMatch(/--chown=appuser:nodejs/);
    });

    test('dependencies stage is minimal', async () => {
      const dockerfile = await readTemplate('base/Dockerfile.base');

      // Deps stage should only install dependencies
      const depsStage = dockerfile.match(/FROM.*AS deps([\s\S]*?)(?=FROM)/m);
      expect(depsStage).toBeTruthy();

      // Should not copy entire source code
      expect(depsStage[0]).not.toMatch(/COPY \. \./);

      // Should copy package files
      expect(depsStage[0]).toMatch(/COPY package.*\.json/);
    });
  });

  describe('Container Name Security', () => {
    test('container names use project placeholders', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Container name should use template variable
        expect(content).toMatch(/container_name:\s+{{PROJECT_NAME}}-/);
      }
    });
  });

  describe('Volume Security', () => {
    test('development volumes are commented out by default', async () => {
      const composeFiles = [
        'tools/figma-make/docker-compose.yml',
        'tools/lovable/docker-compose.yml',
        'tools/bolt/docker-compose.yml'
      ];

      for (const file of composeFiles) {
        const content = await readTemplate(file);

        // Volume mounts should be commented for production safety
        if (content.includes('volumes:')) {
          const volumesSection = content.match(/volumes:[\s\S]*?(?=\n\S|\n$)/);
          if (volumesSection) {
            // Check if it's commented (optional for development)
            const lines = volumesSection[0].split('\n');
            const hasCommentedVolumes = lines.some(line => line.trim().startsWith('#'));

            // Either no volumes or they're commented
            expect(hasCommentedVolumes || !volumesSection[0].includes('./dist')).toBe(true);
          }
        }
      }
    });
  });
});

describe('Security Best Practices Compliance', () => {
  test('templates follow principle of least privilege', async () => {
    const dockerfile = await readTemplate('base/Dockerfile.base');

    // Non-root user should be created
    expect(dockerfile).toMatch(/adduser.*appuser/);

    // User switch should happen before CMD
    const userIndex = dockerfile.indexOf('USER appuser');
    const cmdIndex = dockerfile.indexOf('CMD');
    expect(userIndex).toBeLessThan(cmdIndex);
    expect(userIndex).toBeGreaterThan(0);
  });

  test('minimal attack surface in production image', async () => {
    const dockerfile = await readTemplate('base/Dockerfile.base');

    // Should use alpine (minimal base image)
    expect(dockerfile).toMatch(/alpine/);

    // Should not install unnecessary packages in production
    const productionStage = dockerfile.match(/FROM.*AS production[\s\S]*$/m);

    // Production stage should only install serve if needed for static builds
    if (productionStage[0].includes('npm install -g')) {
      expect(productionStage[0]).toMatch(/{{#if STATIC_BUILD}}/);
    }
  });

  test('security scanning would pass (no obvious vulnerabilities)', async () => {
    const dockerfile = await readTemplate('base/Dockerfile.base');

    // Check for common anti-patterns
    expect(dockerfile).not.toMatch(/chmod 777/);
    expect(dockerfile).not.toMatch(/--disable-sandbox/);
    expect(dockerfile).not.toMatch(/su root/);
  });
});
