global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['{{PROJECT_NAME}}-nginx:80']

  - job_name: 'app'
    static_configs:
      - targets: ['{{PROJECT_NAME}}-prod:80']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']