services:
  # Development service with hot reload
  # Optimized for Figma projects with complex UI dependencies
  app-dev:
    image: node:18-alpine
    container_name: "{{PROJECT_NAME}}-dev"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Use named volume for node_modules to avoid cross-platform issues
      - node_modules:/app/node_modules
      # Exclude node_modules from source mount using anonymous volume
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      # Increase memory for complex UI builds
      - NODE_OPTIONS=--max-old-space-size=4096
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - "{{PROJECT_NAME}}-network"

  # Production service using the local Dockerfile
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: "{{PROJECT_NAME}}-prod"
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - "{{PROJECT_NAME}}-network"
    profiles:
      - production

  # Optional: Nginx reverse proxy for advanced development scenarios
  nginx-dev:
    image: nginx:alpine
    container_name: "{{PROJECT_NAME}}-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-dev
    restart: unless-stopped
    networks:
      - "{{PROJECT_NAME}}-network"
    profiles:
      - proxy

volumes:
  # Named volume for node_modules to improve performance
  # Critical for projects with large UI dependency trees
  node_modules:
    driver: local

networks:
  "{{PROJECT_NAME}}-network":
    driver: bridge
    name: "{{PROJECT_NAME}}-network"