name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_ENV: test
  CI: true

jobs:
  # Security and dependency scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Run security scan with CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # Linting and code quality
  lint:
    name: Lint & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check package.json format
        run: node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"

      - name: Validate template files
        run: |
          echo "Validating template structure..."
          if [ ! -d "templates" ]; then
            echo "❌ Templates directory not found"
            exit 1
          fi
          
          for template in templates/*/; do
            if [ -d "$template" ]; then
              echo "✅ Validating template: $(basename $template)"
              # Check for required files
              if [ ! -f "$template/Dockerfile" ]; then
                echo "❌ Missing Dockerfile in $template"
                exit 1
              fi
              if [ ! -f "$template/docker-compose.yml" ]; then
                echo "❌ Missing docker-compose.yml in $template"
                exit 1
              fi
              echo "✅ Template $(basename $template) is valid"
            fi
          done

  # Matrix testing across Node.js versions
  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    needs: [security, lint]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 21]
        include:
          - os: ubuntu-latest
            node-version: 18
            upload-coverage: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage --coverageReporters=text-lcov --coverageReporters=json

      - name: Test CLI functionality
        shell: bash
        run: |
          echo "Testing CLI help command..."
          node figma-docker-init.js --help || echo "Help command test completed"
          
          echo "Testing CLI version command..."
          node figma-docker-init.js --version || echo "Version command test completed"
          
          echo "Testing CLI list templates..."
          node figma-docker-init.js --list || echo "List templates test completed"

      - name: Upload coverage to Codecov
        if: matrix.upload-coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  # Build and package verification
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test package installation
        run: |
          # Test global installation simulation
          npm pack
          PACKAGE_FILE=$(ls *.tgz)
          echo "Package created: $PACKAGE_FILE"
          
          # Verify package contents
          tar -tzf $PACKAGE_FILE | head -20
          
          # Test if package can be installed
          mkdir test-install
          cd test-install
          npm init -y
          npm install ../$PACKAGE_FILE
          
          # Test if CLI is accessible
          npx figma-docker-init --help || echo "CLI test completed"

      - name: Verify template integrity
        run: |
          echo "Verifying template file integrity..."
          
          for template_dir in templates/*/; do
            if [ -d "$template_dir" ]; then
              template_name=$(basename "$template_dir")
              echo "Checking template: $template_name"
              
              # Check Docker files are valid
              if [ -f "$template_dir/Dockerfile" ]; then
                echo "✅ Dockerfile found for $template_name"
                # Basic Dockerfile syntax check
                if grep -q "FROM" "$template_dir/Dockerfile"; then
                  echo "✅ Dockerfile has FROM instruction"
                else
                  echo "❌ Invalid Dockerfile in $template_name"
                  exit 1
                fi
              fi
              
              # Check docker-compose.yml is valid YAML
              if [ -f "$template_dir/docker-compose.yml" ]; then
                echo "✅ docker-compose.yml found for $template_name"
                # Install yq for YAML validation if not present
                if command -v yq >/dev/null 2>&1; then
                  yq eval . "$template_dir/docker-compose.yml" > /dev/null
                  echo "✅ docker-compose.yml is valid YAML"
                else
                  echo "⚠️ YAML validation skipped (yq not available)"
                fi
              fi
              
              echo "✅ Template $template_name verified"
            fi
          done

  # Semantic Release (only on main branch)
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            dist/*.tgz
          retention-days: 30
          if-no-files-found: warn

  # Notification and status reporting
  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [security, lint, test, build, release]
    if: always()
    steps:
      - name: Report Pipeline Status
        run: |
          echo "=== CI/CD Pipeline Status Report ==="
          echo "Security Scan: ${{ needs.security.result }}"
          echo "Lint & Code Quality: ${{ needs.lint.result }}"
          echo "Tests: ${{ needs.test.result }}"
          echo "Build & Package: ${{ needs.build.result }}"
          echo ""
          
          if [[ "${{ needs.security.result }}" == "success" && 
                "${{ needs.lint.result }}" == "success" && 
                "${{ needs.test.result }}" == "success" && 
                "${{ needs.build.result }}" == "success" ]]; then
            echo "🎉 All pipeline stages completed successfully!"
            echo "Package is ready for deployment."
          else
            echo "❌ Pipeline completed with failures."
            echo "Please review the failed stages before proceeding."
          fi